version: "3.7"
services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local-wire-middleware
    command: -jar DynamoDBLocal.jar -sharedDb -inMemory -port 8005
    ports:
      - "8005:8005"

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - "8004:8001"
    environment:
      DYNAMO_ENDPOINT: "http://dynamodb-local:8005"
      AWS_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: key
      AWS_SECRET_ACCESS_KEY: secret
    depends_on:
      - dynamodb-local
